exclude:
 - README.md
 - node_modules
 - CNAME
title: The Grove
permalink: /news/:year/:month/:day/:title/
paginate_path: /news/page/:num/
paginate: 5
facebook: https://www.facebook.com/groveatx
twitter: https://twitter.com/GroveATX
markdown: rdiscount
